services:
  spotify-to-plex:
    image: ghcr.io/lammersbjorn/spotify-to-plex:latest
    container_name: spotify-to-plex
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/logs
    healthcheck:
      test: ["CMD", "poetry", "run", "spotify-to-plex", "healthcheck"]
      interval: 1h
      timeout: 10s
      retries: 3
      start_period: 30s
