services:
  spotify-to-plex:
    image: ghcr.io/lammersbjorn/spotify-to-plex:latest
    container_name: spotify-to-plex
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./cache:/cache # Persist cache data
      - ./logs:/app/logs # Persist logs
    healthcheck:
      test: ["CMD", "poetry", "run", "spotify-to-plex", "diagnose"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    user: appuser
